# List of known valid licenses
ValidLicenses = [
	'0BSD',
	'AAL',
	'Abstyles',
	'Adobe',
	'ADSL',
	'AFL',
	'Afmparse',
	'AGPLv1',
	'AGPLv3',
	'AGPLv3+',
	'AGPLv3 with exceptions',
	'AGPL-1.0',
	'AGPL-1.0-or-later',
	'AGPL-3.0',
	'AGPL-3.0-or-later',
	'AMDPLPA',
	'AML',
	'AMPAS BSD',
	'ANTLR-PD',
	'APAFML',
	'App-s2p',
	'APSL 2.0',
	'ARL',
	'Array',
	'Artistic 2.0',
	'Artistic clarified',
	'ASL 1.0',
	'ASL 1.1',
	'ASL 2.0',
	'ASL-1.0',
	'ASL-1.1',
	'ASL-2.0',
	'Apache-2.0',
	'Bahyph',
	'Barr',
	'Beerware',
	'BeOpen',
	'Bibtex',
	'BitTorrent',
	'Boost',
	'Borceux',
	'BSD',
	'BSD-2-Clause-Patent',
	'BSD Protection',
	'BSD with advertising',
	'BSD with attribution',
	'CATOSL',
	'CC0',
	'CeCILL',
	'CeCILL-B',
	'CeCILL-C',
	'CDDL-1.0',
	'CDDL-1.1',
	'CNRI',
	'Condor',
	'Copyright only',
	'CPAL',
	'CPL',
	'CPM',
	'CRC32',
	'Crossword',
	'Crystal Stacker',
	'Cube',
	'diffmark',
	'DMIT',
	'DOC',
	'Dotseqn',
	'DSDP',
	'dvipdfm',
	'DWPL',
	'ECL 1.0',
	'ECL 2.0',
	'eCos',
	'EFL 2.0',
	'eGenix',
	'Entessa',
	'EPICS',
	'EPL-1.0',
	'EPL-2.0',
	'ERPL',
	'EU Datagrid',
	'EUPL 1.1',
	'EUPL 1.2',
	'Eurosym',
	'Fair',
	'FDK-AAC',
	'FSFAP',
	'FSFUL',
	'FSFULLR',
	'FTL',
	'Giftware',
	'GL2PS',
	'Glide',
	'Glulxe',
	'gnuplot',
	'GPL+',
	'GPL+ or Artistic',
	'GPL+ with exceptions',
	'GPLv1',
	'GPLv2 or Artistic',
	'GPLv2+ or Artistic',
	'GPLv2',
	'GPLv2 with exceptions',
	'GPLv2+',
	'GPLv2+ with exceptions',
	'GPLv3',
	'GPLv3 with exceptions',
	'GPLv3+',
	'GPLv3+ with exceptions',
	'GPL-2.0',
	'GPL-2.0-or-later',
	'GPL-3.0',
	'GPL-3.0-or-later',
	'HaskellReport',
	'HSRL',
	'IBM',
	'IJG',
	'ImageMagick',
	'iMatix',
	'Imlib2',
	'Inner-Net',
	'Intel ACPI',
	'Interbase',
	'ISC',
	'Jabber',
	'JasPer',
	'JPython',
	'Julius',
	'Knuth',
	'Latex2e',
	'LBNL BSD',
	'Leptonica',
	'LGPLv2',
	'LGPLv2 with exceptions',
	'LGPLv2+',
	'LGPLv2+ or Artistic',
	'LGPLv2+ with exceptions',
	'LGPLv3',
	'LGPLv3 with exceptions',
	'LGPLv3+',
	'LGPLv3+ with exceptions',
	'LGPL-2.0',
	'LGPL-2.0-or-later',
	'LGPL-2.1',
	'LGPL-2.1-or-later',
	'LGPL-3.0',
	'LGPL-3.0-or-later',
	'Lhcyr',
	'libtiff',
	'LLGPL',
	'Logica',
	'LOSLA',
	'LPL',
	'LPPL',
	'MakeIndex',
	'mecab-ipadic',
	'midnight',
	'Minpack',
	'MirOS',
	'MIT',
	'MIT-0',
	'MITNFA',
	'MIT with advertising',
	'mod_macro',
	'Motosoto',
	'MPLv1.0',
	'MPLv1.1',
	'MPLv2.0',
	'MS-PL',
	'MS-RL',
	'MTLL',
	'Mup',
	'Naumen',
	'NCSA',
	'NetCDF',
	'Netscape',
	'Newmat',
	'Newsletr',
	'NGPL',
	'NISTSL',
	'NLPL',
	'Nmap',
	'Nokia',
	'NOSL',
	'Noweb',
	'OGL',
	'OML',
	'OpenLDAP',
	'OpenPBS',
	'OpenSSL',
	'OReilly',
	'OSL 1.0',
	'OSL 1.1',
	'OSL 2.0',
	'OSL 2.1',
	'OSL 3.0',
	'Par',
	'Phorum',
	'PHP',
	'PlainTeX',
	'Plexus',
	'PostgreSQL',
	'psfrag',
	'psutils',
	'Public Domain',
	'Python',
	'Qhull',
	'QPL',
	'radvd',
	'Rdisc',
	'REX',
	'RiceBSD',
	'Romio',
	'RPSL',
	'RSA',
	'Rsfs',
	'Ruby',
	'Saxpath',
	'Sequence',
	'SCEA',
	'SCRIP',
	'Sendmail',
	'Sleepycat',
	'SISSL',
	'SLIB',
	'SNIA',
	'softSurfer',
	'SPL',
	'STMPL',
	'SWL',
	'TCGL',
	'TCL',
	'Teeworlds',
	'TGPPL',
	'TGPPL with exceptions',
	'Threeparttable',
	'TMate',
	'Tolua',
	'TORQUEv1.1',
	'TOSL',
	'TPDL',
	'TPL',
	'TTWL',
	'Tumbolia',
	'UCAR',
	'UCD',
	'Unicode',
	'Unlicense',
	'UPL',
	'Vim',
	'VNLSL',
	'VOSTROM',
	'VSL',
	'W3C',
	'Webmin',
	'Wsuipa',
	'WTFPL',
	'wxWidgets',
	'wxWindows',
	'Xerox',
	'xinetd',
	'xpp',
	'XSkat',
	'YPLv1.1',
	'Zed',
	'Zend',
	'zlib',
	'zlib with acknowledgement',
	'ZPLv1.0',
	'ZPLv2.0',
	'ZPLv2.1',
	# Documentation licenses
	'CDL',
	'FBSDDL',
	'GFDL',
	'IEEE',
	'LDPL',
	'OFSFDL',
	'Open Publication',
	'Public Use',
	'Verbatim',
	# Content licenses
	'CC-BY',
	'CC-BY-ND',
	'CC-BY-SA',
	'DL-DE-BY',
	'DMTF',
	'DSL',
	'EFML',
	'Free Art',
	'GeoGratis',
	'Green OpenMusic',
	'OAL',
	'Ouverte',
	'PDDL-1.0',
	# Font licenses
	'AMS',
	'Arphic',
	'AHFL',
	'Baekmuk',
	'Bitstream Vera',
	'Charter',
	'DoubleStroke',
	'ec',
	'Elvish',
	'Hershey',
	'HOFL',
	'IPA',
	'Liberation',
	'Lucida',
	'MgOpen',
	'mplus',
	'OFL',
	'PTFL',
	'Punknova',
	'STIX',
	'Utopia',
	'Wadalab',
	'XANO',
	# Others
	'Redistributable, no modification permitted',
	'Freely redistributable without restriction',
	'distributable',
]
