# OpenMandriva configuration for rpmlint

# Allow a number of errors for now, since rpmlint filters require
# more tweaking
# Ultimately that should be set to -1 (fail on any error, allow warnings)
BadnessThreshold = 100

# Filename extension to look for when checking that files that should
# be compressed are indeed compressed
CompressExtension = "zst"

# Kernel modules belong into the kernel
KernelModuleRPMsOK = false

MaxLineLength = 80

ValidSrcPerms = [
	"0o644",
	"0o664",
]

SystemLibPaths = [
	"/lib",
	"/usr/lib",
	"/usr/lib/qt6/lib",
	"/lib64",
	"/usr/lib64",
	"/usr/lib64/qt6/lib",
]

# Additional checks to be run
Checks = [
# We may want to add this at some point, but it has
# additional dependencies
#	"BashismsCheck",
	"PAMModulesCheck",
	"TmpFilesCheck",
	"SysVInitOnSystemdCheck",
# This is a Fedora module checking libpackage naming
# policies -- it could be useful, but would need to be
# adapted to OpenMandriva naming conversions first.
#	"SharedLibraryPolicyCheck",
]

ValidEmptyShells = [
	"/usr/sbin/ldconfig",
	"/sbin/ldconfig",
]

ValidShells = [
	"<lua>",
	"/bin/sh",
	"/usr/bin/sh",
	"/bin/bash",
	"/usr/bin/bash",
	"/usr/sbin/ldconfig",
	"/usr/bin/perl",
	"/usr/bin/python",
]

# Checks that are allowed to fail
Filters = [
	# We don't use the buildroot tag
	'.*no-buildroot-tag.*',
	# ABF signs packages after rpmlint has run
	' no-signature',
	# This check enforces Fedora style naming, we prefer ours
	' no-major-in-name ',
	# Requires-on-release are actually a good thing...
	' requires-on-release',
	# Packager is set by abf
	' no-packager-tag',
	# Relax checks on autogenerated debug packages
	'-debug(info|source).* no-documentation',
	'-debuginfo.* /usr/lib/debug/',
	'-debugsource.* /usr/src/debug/',
	'-debuginfo.* description-line-too-long',
	'-debuginfo.* unstripped-binary-or-object',
	'-debuginfo.* statically-linked-binary',
	'-debuginfo.* dangling-relative-symlink',
	# SUSEism - doesn't allow ghost files without creating them in %post
	' postin-without-ghost-file-creation ',
	' ghost-files-without-postin',
	# %defattr is obsolete, no need to enforce it
	'files-attr-not-set',
	# desktop files shouldn't have a shebang
	'script-without-shebang .*\.desktop$',
	# No need to run explicit ldconfig - triggers take care of it in OM
	'postin-without-ldconfig',
	'postun-without-ldconfig',
	'library-without-ldconfig-postin',
	'library-without-ldconfig-postun',
	# install-info is handled by triggers in OM
	' info-files-without-install-info-postin',
	' info-files-without-install-info-postun',
	' postin-without-install-info ',
	# 0700 dir perms are ok in some cases
	'non-standard-dir-perm /etc/.* 700',
	'non-standard-dir-perm /var/lib/.* 700',
	# We don't use %changelog - use "git log" instead...
	'no-changelogname-tag',
	# More often than not, this is intentional
	' conffile-without-noreplace-flag ',
	# Many applications these days have an interactive help
	# system instead of traditional documentation
	' no-documentation',
	# GIR stuff isn't recognizable as a library
	'.*gir.*: W: only-non-binary-in-usr-lib',
	# No idea why that should be an error? Surely packages not
	# containing binaries are useful.
	' no-binary',
	# Our library naming policy diverges from the Fedora policy
	# checked for by rpmlint
	' shlib-policy-name-error',
]
